"""
Error Log → GitHub Issues — создаёт баг-репорты из логов OpenClaw.
"""
import os, re, json, logging, hashlib
from pathlib import Path
from datetime import datetime, timedelta
from dotenv import load_dotenv

logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')
log = logging.getLogger(__name__)

LOG_DIR = Path.home() / '.openclaw' / 'logs'
SEEN_FILE = Path(__file__).parent / 'seen_errors.json'
REPO = 'sakura565-afk/openclaw-cursor'

def get_recent_logs(hours=24) -> list:
    logs = []
    if not LOG_DIR.exists():
        return logs
    cutoff = datetime.now() - timedelta(hours=hours)
    for log_file in LOG_DIR.glob('*.log'):
        if log_file.stat().st_mtime > cutoff.timestamp():
            logs.append(log_file.read_text(encoding='utf-8', errors='ignore'))
    return logs

def parse_errors(text: str) -> list:
    error_blocks = []
    pattern = re.compile(
        r'(.{0,200}(?:ERROR|EXCEPTION|FATAL|FAIL).{0,500})',
        re.IGNORECASE | re.DOTALL
    )
    for match in pattern.finditer(text):
        block = match.group(1).strip().replace('\n', ' ')[:500]
        error_blocks.append(block)
    return error_blocks

def error_hash(error_text: str) -> str:
    return hashlib.sha256(error_text.encode()).hexdigest()[:16]

def main():
    load_dotenv()
    api_key = os.getenv('COMPOSIO_API_KEY')
    if not api_key:
        log.error("COMPOSIO_API_KEY not set"); return
    
    log.info("Parsing OpenClaw logs...")
    logs_text = '\n'.join(get_recent_logs())
    errors = parse_errors(logs_text)
    log.info(f"Found {len(errors)} error blocks")
    
    seen = {}
    if SEEN_FILE.exists():
        seen = json.loads(SEEN_FILE.read_text())
    
    seen_errors = seen.get('errors', {})
    new_count = 0
    
    for error in errors:
        eh = error_hash(error)
        if eh in seen_errors:
            continue
        
        # Determine error type
        if 'Connection' in error or 'timeout' in error.lower():
            label = 'bug'
            title_prefix = '[Connection]'
        elif 'Permission' in error or 'Auth' in error:
            label = 'bug'
            title_prefix = '[Auth]'
        else:
            label = 'bug'
            title_prefix = '[Error]'
        
        title = f"{title_prefix} {error[:80]}..."
        
        body = f"""## Error Report
**Found:** {datetime.now().isoformat()}
**Hash:** `{eh}`

### Context
```
{error}
```

### Suggested Fix
_Fill in if you know how to fix this error._

---
*Auto-generated by Error Log Agent*
"""
        
        # Create GitHub Issue via Composio
        try:
            from composio_client import ComposioClient
            client = ComposioClient(api_key=api_key)
            result = client.github.create_issue(
                repo=REPO,
                title=title,
                body=body,
                labels=[label]
            )
            log.info(f"Created issue: {title[:50]}")
            seen_errors[eh] = {'title': title[:50], 'created': datetime.now().isoformat()}
            new_count += 1
        except Exception as e:
            log.error(f"Failed to create issue: {e}")
    
    seen['errors'] = seen_errors
    SEEN_FILE.write_text(json.dumps(seen, indent=2))
    log.info(f"Done. New errors: {new_count}, Total tracked: {len(seen_errors)}")

if __name__ == '__main__':
    main()