#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Obsidian Researcher."""
import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

import argparse
import re
from datetime import datetime
from pathlib import Path

VAULT_DEFAULT = Path.home() / "Obsidianstore"
RESULTS_LIMIT = 20
SUMMARIZE_LIMIT = 10

def find_notes_by_content(vault, query, limit=RESULTS_LIMIT):
    results = []
    ql = query.lower()
    for md in vault.rglob("*.md"):
        if ".obsidian" in md.parts or "__pycache__" in md.parts:
            continue
        try:
            c = md.read_text(encoding="utf-8", errors="ignore")
        except:
            continue
        if ql in c.lower():
            lines = c.splitlines()
            matches = [f"Line {i}: {l.strip()[:100]}" for i, l in enumerate(lines, 1) if ql in l.lower()]
            results.append({
                "path": md.relative_to(vault).as_posix(),
                "file": md.name,
                "modified": datetime.fromtimestamp(md.stat().st_mtime).isoformat(),
                "matches": matches[:5]
            })
    results.sort(key=lambda x: x["modified"], reverse=True)
    return results[:limit]

def summarize_topic(vault, topic, limit=SUMMARIZE_LIMIT):
    notes = find_notes_by_content(vault, topic, limit)
    if not notes:
        return f"# Summary: {topic}\n\nNo notes found."
    lines = [f"# Summary: {topic}", f"Found {len(notes)} notes. {datetime.now().isoformat()}", "", "## Sources"]
    for i, n in enumerate(notes, 1):
        lines.append(f"{i}. [[{n['path']}]] - {n['modified'][:10]}")
    lines.append("\n## Key Extracts")
    for n in notes[:5]:
        lines.append(f"\n### {n['file']}")
        lines.append(f"Source: `{n['path']}`")
        for m in n.get("matches", [])[:3]:
            lines.append(m)
    lines.append("\n*Generated by Obsidian Researcher*")
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["search", "summarize", "tags"])
    parser.add_argument("query", nargs="?", default="")
    parser.add_argument("--vault", type=Path, default=VAULT_DEFAULT)
    parser.add_argument("--limit", type=int, default=RESULTS_LIMIT)
    args = parser.parse_args()
    if not args.vault.exists():
        print(f"Vault not found: {args.vault}")
        sys.exit(1)
    if args.command == "search":
        if not args.query:
            print("Query required")
            sys.exit(1)
        res = find_notes_by_content(args.vault, args.query, args.limit)
        print(f"\nSEARCH: {args.query} | Found: {len(res)}")
        for i, r in enumerate(res, 1):
            print(f"{i}. {r['file']} | {r['path']} | {r['modified'][:10]}")
            for m in r["matches"][:3]:
                print(f"   {m}")
    elif args.command == "summarize":
        if not args.query:
            print("Topic required")
            sys.exit(1)
        print(summarize_topic(args.vault, args.query))
    elif args.command == "tags":
        tc = {}
        tp = re.compile(r"#([a-zA-Z0-9_-]+)")
        for md in args.vault.rglob("*.md"):
            if ".obsidian" in md.parts: continue
            try:
                c = md.read_text(encoding="utf-8", errors="ignore")
            except: continue
            for t in tp.findall(c):
                tc[t] = tc.get(t, 0) + 1
        tags = sorted(tc.items(), key=lambda x: x[1], reverse=True)
        print(f"\nTags ({len(tags)}):")
        for t, c in tags[:30]:
            print(f"  #{t}: {c}")

if __name__ == "__main__":
    main()
